image:
  name: gitpod/workspace-full:latest

tasks:
  - init:
      command: pip install -r requirements.txt
      openMode: tab
    command: python app.py
    openMode: tab

  - name: aws-cli
    env: 
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
    openMode: split-right

  - name: Install Terraform
    command: |
      wget https://releases.hashicorp.com/terraform/1.0.9/terraform_1.0.9_linux_amd64.zip
      unzip terraform_1.0.9_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      terraform version    
    openMode: tab

vscode:
  extensions:
    - 42Crunch.vscode-openapi    
    - ms-azuretools.vscode-azureterraform
    - mauve.terraform  

ports:
  - port: 3000
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview